name: build-windows-exe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with spec
        run: |
          pyinstaller --clean --onefile tab2long_henan.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tab2long_henan-exe
          path: dist/tab2long_henan.exe
