name: build-windows-exe
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify project files
        run: |
          dir
          if not exist tab2long_henan.py ( echo tab2long_henan.py missing & exit /b 1 )

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build deps (pinned)
        run: |
          python -m pip install -U pip wheel
          pip install "pandas==2.2.2" "numpy==2.0.2" "openpyxl==3.1.5" "xlrd<2.0" ^
                      "python-dateutil==2.9.0.post0" "pytz==2024.1" "tzdata==2024.1" "et-xmlfile==1.1.0"
          pip install "pyinstaller==6.16.0" pyinstaller-hooks-contrib

      - name: Build (no spec, onefile)
        run: |
          pyinstaller --clean --onefile --name tab2long_henan tab2long_henan.py ^
            --collect-submodules pandas ^
            --collect-submodules numpy ^
            --collect-submodules openpyxl ^
            --collect-submodules xlrd ^
            --collect-data pandas ^
            --collect-data openpyxl

      - name: List dist
        run: dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tab2long_henan-exe
          path: dist/tab2long_henan.exe
